"""empty message

Revision ID: 0a7dd27bbf44
Revises: 9c63a78dafd4
Create Date: 2020-08-25 17:41:57.027385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a7dd27bbf44'
down_revision = '9c63a78dafd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('version_list',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('version_code', sa.String(length=20), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('version_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('version_list')
    # ### end Alembic commands ###
