"""empty message

Revision ID: 1f8252c54909
Revises: 2c8485bee579
Create Date: 2020-08-25 16:56:39.366130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f8252c54909'
down_revision = '2c8485bee579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('version_list',
    sa.Column('version_code', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('version_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('version_list')
    # ### end Alembic commands ###
