"""champion_stat

Revision ID: 412d6cc7bb17
Revises: c0203a53f265
Create Date: 2020-08-31 17:42:21.883301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412d6cc7bb17'
down_revision = 'c0203a53f265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('champion_stat', 'champion_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('champion_stat', 'champion_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
