"""create tables

Revision ID: 94cda7c922ff
Revises: 
Create Date: 2020-08-26 16:41:09.038087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94cda7c922ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('champion_list',
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('champion_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('champion_id'),
    sa.UniqueConstraint('champion_name')
    )
    op.create_table('user_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=180), nullable=False),
    sa.Column('avatar', sa.String(length=80), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('version_list',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('version_code', sa.String(length=20), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('version_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('version_list')
    op.drop_table('user_list')
    op.drop_table('champion_list')
    # ### end Alembic commands ###
