"""empty message

Revision ID: 9de7c5eae906
Revises: 412d6cc7bb17
Create Date: 2020-12-27 13:31:51.877037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9de7c5eae906'
down_revision = '412d6cc7bb17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('champion_spell',
    sa.Column('champion_spell_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('spell_code', sa.Integer(), nullable=False),
    sa.Column('spell_name', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['champion_id'], ['champion_list.champion_id'], ),
    sa.PrimaryKeyConstraint('champion_spell_id')
    )
    op.create_index(op.f('ix_champion_spell_spell_code'), 'champion_spell', ['spell_code'], unique=False)
    op.create_index(op.f('ix_champion_spell_spell_name'), 'champion_spell', ['spell_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_champion_spell_spell_name'), table_name='champion_spell')
    op.drop_index(op.f('ix_champion_spell_spell_code'), table_name='champion_spell')
    op.drop_table('champion_spell')
    # ### end Alembic commands ###
