"""empty message

Revision ID: b3e9ecaba9b5
Revises: 87e0d38272f2
Create Date: 2020-07-15 15:05:46.568566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e9ecaba9b5'
down_revision = '87e0d38272f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_list', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_list', type_='unique')
    # ### end Alembic commands ###
