"""empty message

Revision ID: f91fcfb76659
Revises: 94cda7c922ff
Create Date: 2020-08-27 16:16:35.295009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f91fcfb76659'
down_revision = '94cda7c922ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_list',
    sa.Column('tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('tag_name')
    )
    op.create_table('champion_tag',
    sa.Column('champion_tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['champion_id'], ['champion_list.champion_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag_list.tag_id'], ),
    sa.PrimaryKeyConstraint('champion_tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('champion_tag')
    op.drop_table('tag_list')
    # ### end Alembic commands ###
